### ISSUE TITLE
Finir le projet

### ISSUE THREAD

**Issue by Darkilen** [githly/ISS-live#1]
Finir le projet pour le 23 février.

**Comment by GuillotJessica** [comment]
allez salut ;)

**Comment by metallou** [comment]
La moitié des Issue ont été fermés
Au boulot

**Comment by GuillotJessica** [comment]
bon boulot

Le 19 févr. 2017 19:35, "Kévin CASTEJON" <notifications@github.com> a
écrit :

**Comment by metallou** [comment]
Je ferme pas celui là
C'est  le job de @githly
